# Generated by Django 6.0.6 on 2026-09-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentform', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Check this if you want to post listings/products.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
