# Generated by Django 6.0.6 on 2026-09-18 14:20

import consentform.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentform', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', validators=[consentform.validators.validate_image_extension_and_size]),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/', validators=[consentform.validators.validate_image_extension_and_size]),
        ),
    ]
