# Generated by Django 5.0.6 on 2026-09-22 12:11

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('consentform', 'Category')
    default_categories = [
        {'name': 'Electronics', 'slug': 'electronics'},
        {'name': 'Books & Stationery', 'slug': 'books-stationery'},
        {'name': 'Fashion & Clothing', 'slug': 'fashion-clothing'},
        {'name': 'Services & Tutoring', 'slug': 'services-tutoring'},
        {'name': 'Dorm & Furniture', 'slug': 'dorm-furniture'},
    ]
    for cat in default_categories:
        Category.objects.get_or_create(slug=cat['slug'], defaults={'name': cat['name']})

class Migration(migrations.Migration):

    dependencies = [
        ('consentform', '0006_notification'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]